import { useState } from 'react'
import { usePrototype } from './context'
import { events, people } from './model'
import { Avatar, Avatars, Button, Chips, Empty, Header, Icon } from './ui'

export function EventsScreen() {
  const { empty, setEmpty, go, setEventId, eventId, state } = usePrototype()
  const [category, setCategory] = useState('All')
  const openEvent = (id: string) => { setEventId(id); if (!window.matchMedia('(min-width: 1800px)').matches) go('Event Detail') }
  const visible = events.filter(event => category === 'All' || event.category === category)
  return <div className="pt-events-workspace"><section className="pt-events-feed"><Header title="Events around campus" sub="Find something worth showing up for." /><Chips label="Event category" options={['All', 'Music', 'Food', 'Outdoors']} values={[category]} onChange={([value]) => { setCategory(value); if (value !== 'All') setEventId(events.find(event => event.category === value)!.id) }} /><p className="pt-results-note"><Icon name="pin" size={16} />Around campus · sample events, not live listings</p>{empty ? <Empty title="A quiet calendar" text="No events to show here yet. Try another category." action="Show sample events" onClick={() => setEmpty(false)} /> : <div className="pt-event-grid">{visible.map(event => <article className={`pt-event-card ${event.id === eventId ? 'is-current' : ''}`} key={event.id}><button className="pt-event-image" aria-label={`View ${event.title}`} onClick={() => { openEvent(event.id) }}><img src={`/prototype/${event.image}`} alt={event.category === 'Music' ? 'Live stage with warm concert lighting' : event.category === 'Food' ? 'Coffee being prepared in a café' : 'Sunlight through green woodland'} /><span className="pt-price">{event.price}</span></button><div className="pt-event-copy"><span className="pt-eyebrow">{event.category} · {event.distance}</span><button className="pt-name-link" onClick={() => { openEvent(event.id) }}><h2>{event.title}</h2></button><p className="pt-event-date">{event.when}</p><p><Icon name="pin" size={16} />{event.place}</p><div className="pt-social-context"><Avatars ids={event.people.filter(id => !state.blocked.includes(id))} /><span>{event.people.filter(id => !state.blocked.includes(id)).length} people looking for company</span></div><Button secondary className="pt-wide" onClick={() => { openEvent(event.id) }}>See event & people<Icon name="arrow" size={18} /></Button></div></article>)}</div>}</section><aside className="pt-event-preview"><EventDetail preview /></aside></div>
}
export function EventDetail({ preview = false }: { preview?: boolean }) {
  const { eventId, go, state, setPersonId, dispatch } = usePrototype()
  const event = events.find(e => e.id === eventId) ?? events[0]
  const interested = people.filter(p => event.people.includes(p.id) && !state.blocked.includes(p.id))
  return <><Header title={preview ? "Selected event" : "Event details"} back={preview ? undefined : () => go('Events')} /><article className="pt-event-detail"><img className="pt-detail-hero" src={`/prototype/${event.image}`} alt={`${event.category} event atmosphere; illustrative photo`} /><div className="pt-detail-body"><div><span className="pt-eyebrow">{event.category} · {event.price} · {event.distance}</span><h1>{event.title}</h1><p className="pt-detail-fact"><Icon name="events" />{event.when}</p><p className="pt-detail-fact"><Icon name="pin" />{event.place}</p><p className="pt-description">{event.description}</p><span className="pt-hint">Fictional event · illustrative photography</span></div><section><h2>Find your company</h2>{interested.map(person => <button className="pt-interested-person" key={person.id} onClick={() => { setPersonId(person.id); go('Other User Profile') }}><Avatar person={person} size="small" /><span><strong>{person.name}</strong><small>Looking for someone to go with</small></span><Icon name="arrow" size={16} /></button>)}<Button className="pt-wide" onClick={() => { dispatch({ type: 'draft', patch: { when: 'Later today', date: '2026-09-26', vibe: event.category === 'Music' ? 'Low-key' : event.category, activity: event.activity, people: [], time: '' } }); go('Free Time Match') }}>Find someone to go with</Button></section></div></article></>
}
