import { useState } from 'react'
import { usePrototype } from './context'
import { activities, availableTimes, people, planDate, planTime, validPlan, type Draft } from './model'
import { Avatar, Avatars, Button, Chips, Empty, Header, Icon, Pebble, Ripple } from './ui'

export function PlanSummary({ draft }: { draft: Draft }) {
  const { state } = usePrototype()
  const activity = activities.find(a => a.id === draft.activity)
  return <dl className="pt-plan-summary"><div><dt>Who</dt><dd><Avatars ids={draft.people} /><span>{state.profile.name} (you){draft.people.map(id => `, ${people.find(p => p.id === id)?.first ?? ''}`).join('')}</span></dd></div><div><dt>When</dt><dd>{planDate(draft)}<strong>{planTime(draft)}</strong></dd></div><div><dt>What</dt><dd>{activity?.name ?? 'Choose an activity'}<span>{activity?.duration} · {activity?.cost}</span></dd></div><div><dt>Where</dt><dd>{activity?.place ?? 'Choose a place'}<span>{activity?.point}</span></dd></div>{draft.note && <div><dt>Note</dt><dd>{draft.note}</dd></div>}</dl>
}
export function FreeTime() {
  const { state, dispatch, go } = usePrototype()
  const [step, setStep] = useState(0)
  const { draft } = state
  const headings = ['When are you free?', 'What sounds good?', 'How far would you go?']
  return <><Header title="Who’s free?" sub="Choose when, what, and how far." back={() => step ? setStep(step - 1) : go('Home')} /><div className="pt-free-layout"><section className="pt-pond-panel"><Ripple /><div><h2>Your Pebble is in.</h2><p>Find a little time in common.</p></div><div className="pt-small-note">Demo clock · Sat, Sep 26, 3 PM</div></section><section className="pt-surface pt-preferences"><div className="pt-step-row"><span>STEP {step + 1} OF 3</span><span>{['When', 'Vibe', 'Distance'][step]}</span></div><div className="pt-step-bars">{[0, 1, 2].map(i => <span className={i <= step ? 'is-done' : ''} key={i} />)}</div><h2>{headings[step]}</h2>{step === 0 && <><Chips label="When" options={['Now', 'Later today', 'Tonight', 'Pick a time']} values={[draft.when]} onChange={([when]) => dispatch({ type: 'draft', patch: { when, time: '', date: when === 'Pick a time' ? draft.date : '2026-09-26' } })} />{draft.when === 'Pick a time' ? <div className="pt-form-row"><label>Date<input type="date" value={draft.date} min="2026-09-26" onChange={e => dispatch({ type: 'draft', patch: { date: e.target.value, time: '' } })} /></label><label>Start time<input type="time" value={draft.customTime} onChange={e => dispatch({ type: 'draft', patch: { customTime: e.target.value, time: '' } })} /></label></div> : <p className="pt-hint">{draft.when === 'Tonight' ? 'Tonight · 7–9 PM' : draft.when === 'Now' ? 'This afternoon · from 3 PM' : 'This afternoon · 3–6 PM'}</p>}</>}{step === 1 && <Chips label="Vibe" options={['Low-key', 'Food', 'Active', 'Outdoors', 'Games', 'Study', 'Surprise me']} values={[draft.vibe]} onChange={([vibe]) => dispatch({ type: 'draft', patch: { vibe } })} />}{step === 2 && <><Chips label="Distance" options={['Nearby', '5 miles', '10 miles']} values={[draft.distance]} onChange={([distance]) => dispatch({ type: 'draft', patch: { distance } })} /><p className="pt-hint">From campus. This demo doesn’t use your location.</p><div className="pt-selection-recap"><Icon name="time" /><span>{draft.when} · {draft.vibe} · {draft.distance}</span></div></>}<Button className="pt-wide" disabled={!draft.date || !draft.customTime} onClick={() => step < 2 ? setStep(step + 1) : go('Free Time Match')}>{step < 2 ? 'Continue' : 'Find people'}<Icon name="arrow" /></Button></section></div></>
}
export function Matches() {
  const { state, dispatch, go, empty, setEmpty, setPersonId } = usePrototype()
  const available = people.filter(p => !state.blocked.includes(p.id))
  const selected = state.draft.people
  const toggle = (id: string) => dispatch({ type: 'draft', patch: { people: selected.includes(id) ? selected.filter(p => p !== id) : [...selected, id], time: '' } })
  return <><Header title="Find your people" sub={`${state.draft.when} · ${state.draft.vibe} · ${state.draft.distance}`} back={() => go('Free Time')} />{empty || !available.length ? <Empty title="No overlap just yet" text="Try a wider distance or another time. There’s no rush." action="Adjust free time" onClick={() => { setEmpty(false); go('Free Time') }} /> : <><div className="pt-match-overview"><Ripple count={available.length + 1} compact /><div><h2>{available.length} people overlap with your free time.</h2><p>Choose one person or a small group.</p><span className="pt-small-note">Illustrative matches · availability is simulated</span></div></div><div className="pt-people-list">{available.map(person => <article className={`pt-person-row ${selected.includes(person.id) ? 'is-selected' : ''}`} key={person.id}><button className="pt-avatar-link" aria-label={`View ${person.first}'s profile`} onClick={() => { setPersonId(person.id); go('Other User Profile') }}><Avatar person={person} /></button><div><button className="pt-name-link" onClick={() => { setPersonId(person.id); go('Other User Profile') }}>{person.name}</button><p>{person.overlap}</p><span className="pt-availability"><Icon name="time" size={16} />{state.draft.when === 'Tonight' ? 'Tonight · 7–9 PM' : state.draft.when === 'Pick a time' ? `${planDate(state.draft)} · selected time` : `Today · ${person.time}`}</span></div><button className="pt-select-person" aria-label={`Select ${person.first}`} aria-pressed={selected.includes(person.id)} onClick={() => toggle(person.id)}>{selected.includes(person.id) ? <Icon name="check" /> : '+'}</button></article>)}</div><div className="pt-action-bar"><span>{selected.length ? `${selected.length} ${selected.length === 1 ? 'person' : 'people'} selected` : 'Select someone to continue'}</span><Button disabled={!selected.length} onClick={() => go('Activities')}>Choose an activity<Icon name="arrow" /></Button></div></>}</>
}
export function ActivityPaths() {
  const { state, dispatch, go } = usePrototype()
  const { draft } = state
  if (!draft.people.length) return <><Header title="Make a plan" /><Empty title="Who’s joining you?" text="Choose your people before picking an activity together." action="Choose people" onClick={() => go('Free Time Match')} /></>
  return <><Header title="What should you do?" sub={`You + ${draft.people.map(id => people.find(p => p.id === id)?.first).join(' + ')} · ${draft.when}`} back={() => go('Free Time Match')} /><div className={`pt-path-world pt-path-${draft.activity || 'none'}`} aria-hidden="true"><svg viewBox="0 0 800 120" preserveAspectRatio="none"><path d="M400 20v35M400 40Q180 40 120 120M400 40q0 40 0 80M400 40q220 0 280 80" fill="none" stroke="#c1b594" strokeWidth="14" strokeLinecap="round" /><path d="M400 20v35M400 40Q180 40 120 120M400 40q0 40 0 80M400 40q220 0 280 80" fill="none" stroke="#eee4cb" strokeWidth="8" strokeDasharray="3 8" /></svg><div>{draft.people.map(id => <Pebble key={id} />)}<Pebble /></div></div><div className="pt-activity-grid" role="group" aria-label="Activities">{activities.map(activity => <button key={activity.id} aria-pressed={draft.activity === activity.id} className="pt-activity-card" onClick={() => dispatch({ type: 'draft', patch: { activity: activity.id } })}><span className="pt-activity-icon"><Icon name={activity.icon} size={27} /></span><span><strong>{activity.short}</strong><span>{activity.place}</span><small>{activity.duration} · {activity.cost} · {activity.distance}</small></span>{draft.activity === activity.id && <Icon name="check" />}</button>)}</div><div className="pt-action-bar"><span>{draft.activity ? activities.find(a => a.id === draft.activity)?.name : 'Choose one activity'}</span><Button disabled={!draft.activity} onClick={() => go('Planning')}>Choose a time<Icon name="arrow" /></Button></div></>
}
export function Planning() {
  const { state, dispatch, go } = usePrototype()
  const { draft } = state
  const activity = activities.find(a => a.id === draft.activity)
  if (!draft.people.length || !activity) return <><Header title="Plan the details" /><Empty title="Start with people and an activity" text="A little shared ground makes planning easier." action={draft.people.length ? 'Choose an activity' : 'Choose people'} onClick={() => go(draft.people.length ? 'Activities' : 'Free Time Match')} /></>
  return <><Header title="Choose your shared time" sub={`${planDate(draft)} · ${activity.duration}`} back={() => go('Activities')} /><div className="pt-planning-grid"><section className="pt-surface"><div className="pt-section-heading"><h2>Who’s coming</h2><button className="pt-text-button" onClick={() => go('Free Time Match')}>Edit people</button></div><div className="pt-person-chips"><span className="pt-person-chip"><Avatar person={state.profile} size="small" />You</span>{draft.people.map(id => { const person = people.find(p => p.id === id)!; return <span className="pt-person-chip" key={id}><Avatar person={person} size="small" />{person.first}</span> })}</div><h2 className="pt-section-space">Available start times</h2><p className="pt-hint">Mock availability for this group.</p><div className="pt-time-options" role="group" aria-label="Shared time">{availableTimes(draft).map(time => { const missing = draft.people.filter(id => time.unavailable.includes(id)); return <button key={time.id} disabled={!!missing.length} aria-pressed={draft.time === time.id} onClick={() => dispatch({ type: 'draft', patch: { time: time.id } })}><Icon name="time" /><span><strong>{time.label}</strong><small>{missing.length ? `${missing.map(id => people.find(p => p.id === id)?.first).join(', ')} unavailable` : 'Everyone is free'}</small></span>{draft.time === time.id && <Icon name="check" />}</button> })}</div><button className="pt-text-button" onClick={() => go('Free Time')}>Change day or time window</button></section><aside className="pt-surface pt-plan-aside"><span className="pt-activity-icon"><Icon name={activity.icon} size={28} /></span><h2>{activity.name}</h2><p><Icon name="pin" size={18} />{activity.place}</p><p>{activity.point}</p><p>{activity.cost} · {activity.distance}</p><button className="pt-text-button" onClick={() => go('Activities')}>Change activity</button><label className="pt-section-space">A note for the group <span>(optional)</span><textarea maxLength={180} value={draft.note} placeholder="I’ll bring a deck of cards…" onChange={e => dispatch({ type: 'draft', patch: { note: e.target.value } })} /></label></aside></div><div className="pt-action-bar"><span>{draft.time ? planTime(draft) : 'Choose a time that works for everyone'}</span><Button disabled={!validPlan(draft, state.blocked)} onClick={() => go('Review')}>Review plan<Icon name="arrow" /></Button></div></>
}
export function ReviewPlan() {
  const { state, dispatch, go } = usePrototype()
  const ready = validPlan(state.draft, state.blocked)
  return <><Header title="Ready to make it a plan?" sub="Check the details together." back={() => go('Planning')} /><section className="pt-surface pt-review"><div className="pt-section-heading"><h2>Your plan</h2><span className="pt-badge">Proposed · demo</span></div><PlanSummary draft={state.draft} /><button className="pt-text-button" onClick={() => go('Planning')}>Edit plan details</button><p className="pt-hint">Confirming updates only this prototype. No invitations are sent.</p><Button className="pt-wide" disabled={!ready} onClick={() => { dispatch({ type: 'confirm' }); go('Confirmed') }}>Confirm plan<Icon name="check" /></Button>{!ready && <p className="pt-hint">Choose people, an activity, and a shared time first.</p>}</section></>
}
export function ConfirmedPlan() {
  const { state, dispatch, go } = usePrototype()
  if (!state.plan) return <><Header title="Your plan" /><Empty title="A plan starts with a little overlap" text="Choose a time, some people, and something to do." action="Start a plan" onClick={() => go('Free Time')} /></>
  const activity = activities.find(a => a.id === state.plan!.activity)!
  return <><Header title="You have a plan." sub="All the details, together in your chat." /><section className="pt-surface pt-review"><div className="pt-gathering" aria-hidden="true"><Pebble /><span><Icon name={activity.icon} size={40} /></span>{state.plan.people.map(id => <Pebble key={id} />)}</div><div className="pt-section-heading"><h2>{activity.name}</h2><span className="pt-badge">Confirmed</span></div><PlanSummary draft={state.plan} /><Button className="pt-wide" onClick={() => go('Chat')}>Open group chat<Icon name="messages" /></Button><button className="pt-text-button" onClick={() => { dispatch({ type: 'edit-plan' }); go('Planning') }}>Change plan</button><p className="pt-hint">Demo confirmation · not sent or saved outside this session.</p></section></>
}
