import { mockCurrentEvents } from './current-events-fixture'
import { expect, test, type Page } from '@playwright/test'

async function scene(page: Page, name: string) { await page.getByLabel('Review scene').selectOption(name) }
async function startPlan(page: Page) {
  await page.goto('/free-time')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Find people', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Choose an activity' })).toBeDisabled()
  await page.getByRole('button', { name: 'Select Jamie', exact: true }).click()
  await page.getByRole('button', { name: 'Select Aaron', exact: true }).click()
  await page.getByRole('button', { name: 'Choose an activity' }).click()
  await page.getByRole('button', { name: /^Coffee Campus/ }).click()
  await page.getByRole('button', { name: 'Choose a time', exact: true }).click()
}
for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
  test(`connected planning path, edit and chat at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport)
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await startPlan(page)
    await expect(page.getByRole('button', { name: /5:00–5:45 PM/ })).toBeDisabled()
    await expect(page.getByRole('button', { name: 'Review plan' })).toBeDisabled()
    await page.getByRole('button', { name: /4:00–4:45 PM/ }).click()
    await page.getByLabel('A note for the group').fill('Meet by the window.')
    await page.getByRole('button', { name: 'Review plan' }).click()
    await expect(page.getByText('Meet by the window.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Edit plan details' }).click()
    await expect(page.getByRole('button', { name: /4:00–4:45 PM/ })).toHaveAttribute('aria-pressed', 'true')
    await page.getByRole('button', { name: 'Review plan' }).click()
    await page.getByRole('button', { name: 'Confirm plan', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'You have a plan.' })).toBeVisible()
    await page.getByRole('button', { name: 'Open group chat' }).click()
    await expect(page.locator('.pt-shared-plan')).toContainText('Confirmed')
    await expect(page.locator('.pt-shared-plan')).toContainText('4:00–4:45 PM')
    await page.getByLabel('Message', { exact: true }).fill('See you there!')
    await page.getByRole('button', { name: 'Send', exact: true }).click()
    await expect(page.locator('.pt-chat-bubble').filter({ hasText: /^See you there!$/ })).toBeVisible()
    await page.getByRole('link', { name: 'Messages', exact: true }).click()
    await expect(page.locator('.pt-conversation')).toHaveCount(6)
    await expect(page.locator('.pt-conversation').first()).toContainText('See you there!')
    await page.locator('.pt-conversation').first().click()
    await page.getByRole('button', { name: 'Change plan' }).click()
    await page.getByRole('button', { name: 'Change activity' }).click()
    await page.getByRole('button', { name: /^Walk Main quad/ }).click()
    await page.getByRole('button', { name: 'Choose a time', exact: true }).click()
    await page.getByRole('button', { name: 'Review plan' }).click()
    await page.getByRole('button', { name: 'Confirm plan', exact: true }).click()
    if (viewport.width > 800) await page.getByRole('button', { name: 'Account menu' }).click()
    await page.getByRole('link', { name: 'Profile', exact: true }).click()
    await expect(page.locator('.pt-profile-plan')).toContainText('A walk around campus')
    await page.getByRole('link', { name: 'Messages', exact: true }).click()
    await expect(page.locator('.pt-conversation')).toHaveCount(6)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
  })
}
test('onboarding skip, all chapters, unique rewards and ordinary profile editing', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/onboarding')
  await page.getByRole('button', { name: 'Skip animation' }).click()
  await expect(page.getByRole('button', { name: 'Complete chapter' })).toBeDisabled()
  await page.getByRole('button', { name: 'Use demo photo' }).click()
  await page.getByLabel('Display name', { exact: true }).fill('Sam')
  await page.getByLabel('A short bio').fill('Music, games, and getting outside.')
  await page.getByRole('button', { name: 'Complete chapter' }).click()
  await page.getByRole('button', { name: 'Skip animation' }).click()
  await expect(page.locator('.pt-pouch-count')).toContainText('10')
  await page.getByRole('button', { name: 'Basic profile, completed' }).click()
  await page.getByRole('button', { name: 'Save & continue' }).click()
  await page.getByRole('button', { name: 'Skip animation' }).click()
  await expect(page.locator('.pt-pouch-count')).toContainText('10')
  await page.getByRole('button', { name: 'Music', exact: true }).click()
  await page.getByRole('button', { name: 'Coffee', exact: true }).click()
  await page.getByRole('button', { name: 'Complete chapter' }).click()
  await page.getByRole('button', { name: 'Skip animation' }).click()
  await page.getByRole('button', { name: 'Meet new people', exact: true }).click()
  await page.getByRole('button', { name: 'Complete chapter' }).click()
  await page.getByRole('button', { name: 'Skip animation' }).click()
  await page.getByRole('button', { name: 'Afternoons', exact: true }).click()
  await page.getByRole('button', { name: 'Complete chapter' }).click()
  await page.getByRole('button', { name: 'Skip animation' }).click()
  await expect(page.getByRole('heading', { name: 'Your Pebble is ready.' })).toBeVisible()
  await expect(page.locator('.pt-pouch-count')).toContainText('40')
  await page.getByRole('button', { name: 'Enter Pebble' }).click()
  await expect(page.getByRole('heading', { name: 'Your Pebble community' })).toBeAttached()
  await expect(page.locator('[data-upgrade]')).toHaveCount(0)
  await expect(page.getByLabel('Pebble balance', { exact: true })).toContainText('40')
  await page.getByRole('link', { name: 'Profile', exact: true }).click()
  await page.getByRole('button', { name: 'Edit profile' }).click()
  await page.getByLabel('Display name', { exact: true }).fill('Sam Lee')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('heading', { name: 'Sam Lee', exact: true })).toBeVisible()
  await expect(page.locator('.pt-origin')).toHaveCount(0)
})
test('cinematic finishes; reduced motion bypasses it and disables movement', async ({ page }) => {
  await page.goto('/onboarding')
  await expect(page.locator('.pt-enormous-shadow')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Basic profile', exact: true })).toBeVisible({ timeout: 8000 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.reload()
  await expect(page.locator('.pt-cinematic')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Basic profile', exact: true })).toBeVisible()
  await scene(page, 'Free Time')
  expect(await page.locator('.pt-ripple-stone').evaluate(element => getComputedStyle(element).animationName)).toBe('none')
  await scene(page, 'Login')
  const curious = page.getByRole('button', { name: 'Say hello to the curious Pebble' })
  const oldClass = await curious.getAttribute('class')
  await curious.click()
  await expect(curious).toHaveClass(/is-hidden/)
  await expect(curious).not.toHaveClass(/is-hidden/, { timeout: 4500 })
  expect(await curious.getAttribute('class')).not.toBe(oldClass)
})
test('all scenes fit a narrow phone; filters, empty states, reporting and blocking work', async ({ page }) => {
  await mockCurrentEvents(page)
  await page.setViewportSize({ width: 360, height: 800 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const values = await page.getByLabel('Review scene').locator('option').allTextContents()
  for (const value of values) {
    await scene(page, value)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), value).toBe(true)
  }
  await scene(page, 'Events')
  await page.getByRole('button', { name: 'Music', exact: true }).click()
  await expect(page.locator('.ev-event-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Outdoors', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A quiet calendar' })).toBeVisible()
  await page.getByLabel('Empty states').check()
  await scene(page, 'Messages')
  await expect(page.getByRole('heading', { name: 'Your conversations start here' })).toBeVisible()
  await scene(page, 'Free Time Match')
  await expect(page.getByRole('heading', { name: 'No overlap just yet' })).toBeVisible()
  await page.getByLabel('Empty states').uncheck()
  await scene(page, 'Other User Profile')
  await page.getByRole('button', { name: 'Report user', exact: true }).click()
  await page.getByRole('combobox', { name: 'Reason', exact: true }).selectOption('Harassment')
  await page.getByRole('button', { name: 'Submit demo report' }).click()
  await expect(page.getByRole('status')).toContainText('No real report was filed.')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: 'Block user', exact: true }).click()
  await page.getByRole('button', { name: 'Block in demo', exact: true }).click()
  await scene(page, 'Free Time Match')
  await expect(page.getByRole('button', { name: 'Select Jamie', exact: true })).toHaveCount(0)
  await scene(page, 'Settings')
  await page.getByRole('button', { name: 'Unblock', exact: true }).click()
  await page.getByLabel('Share my availability').uncheck()
  await scene(page, 'Home')
  await scene(page, 'Settings')
  await expect(page.getByLabel('Share my availability')).not.toBeChecked()
})

test('settings switches retain session changes and dialogs return focus', async ({ page }) => {
  await page.goto('/settings')
  const notifications = page.getByRole('switch', { name: 'Plan & message notifications', exact: true })
  await expect(notifications).toBeChecked()
  await notifications.focus()
  await page.keyboard.press('Space')
  await expect(notifications).not.toBeChecked()
  await page.getByLabel('Review scene').selectOption('Profile')
  await page.getByLabel('Review scene').selectOption('Settings')
  await expect(notifications).not.toBeChecked()
  const account = page.getByRole('button', { name: /^Account details/ })
  await account.click()
  await expect(page.getByRole('dialog', { name: 'Demo account' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(account).toBeFocused()
  const blocked = page.getByRole('button', { name: /^Blocked users/ })
  await blocked.click()
  await expect(page.getByRole('dialog', { name: 'Blocked users' })).toContainText('No blocked users in this session.')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(blocked).toBeFocused()
  await page.getByRole('button', { name: 'Log out of demo', exact: true }).click()
  await expect(page).toHaveURL('/login')
})

test('registration stays local, custom time is preserved, and unread state clears', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const requests: string[] = []
  page.on('request', request => { if (['fetch', 'xhr'].includes(request.resourceType())) requests.push(request.url()) })
  await page.goto('/register')
  await page.getByLabel('Email', { exact: true }).fill('demo@example.com')
  await page.getByLabel('Password', { exact: true }).fill('fake-password')
  await page.getByRole('button', { name: 'Create demo account' }).click()
  await expect(page.getByRole('heading', { name: 'Basic profile', exact: true })).toBeVisible()
  await scene(page, 'Free Time')
  await page.getByRole('button', { name: 'Pick a time', exact: true }).click()
  await page.getByLabel('Date', { exact: true }).fill('2026-10-03')
  await page.getByLabel('Start time', { exact: true }).fill('14:30')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Games', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: '5 miles', exact: true }).click()
  await page.getByRole('button', { name: 'Find people', exact: true }).click()
  await page.getByRole('button', { name: 'Select Maya', exact: true }).click()
  await page.getByRole('button', { name: 'Choose an activity' }).click()
  await page.getByRole('button', { name: /^Board games Student Union/ }).click()
  await page.getByRole('button', { name: 'Choose a time', exact: true }).click()
  await page.getByRole('button', { name: /2:30 PM/ }).click()
  await page.getByRole('button', { name: 'Review plan' }).click()
  await page.goBack()
  await expect(page.getByRole('button', { name: /2:30 PM/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Review plan' }).click()
  await page.getByRole('button', { name: 'Confirm plan', exact: true }).click()
  await expect(page.locator('.pt-plan-summary')).toContainText('Sat, Oct 3')
  await expect(page.locator('.pt-plan-summary')).toContainText('2:30 PM')
  await scene(page, 'Messages')
  await page.getByRole('button', { name: /Jamie Chen I’m free Thursday/ }).click()
  await page.getByRole('link', { name: 'Messages', exact: true }).click()
  await expect(page.locator('.pt-conversation').filter({ hasText: 'Jamie Chen' }).locator('.pt-unread')).toHaveCount(0)
  expect(requests).toEqual([])
})
